_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: c584eebe-eee0-4994-9ab3-3bbbe90504ef
name: practice-movie-site
mail: abc@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /movie-listing
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
